# Generated by Django 5.0.6 on 2024-06-01 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitre_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_ip', models.CharField(blank=True, max_length=20)),
                ('local_ip', models.CharField(blank=True, max_length=20)),
                ('mac_addr', models.CharField(blank=True, max_length=30)),
                ('os_name', models.CharField(blank=True, max_length=50)),
                ('os_version', models.CharField(blank=True, max_length=500)),
                ('os_arch', models.CharField(blank=True, max_length=50)),
                ('processor', models.CharField(blank=True, max_length=50)),
                ('user_name', models.CharField(blank=True, max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttackResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField()),
                ('executed_date', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='screenshots/')),
                ('attack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.attack')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.machine')),
            ],
        ),
    ]
