# Generated by Django 5.0.6 on 2024-06-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_attackresult_result_type_alter_attackresult_attack_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attackresult',
            name='executed_date',
            field=models.DateTimeField(null=True),
        ),
    ]
