# Generated by Django 5.0.6 on 2024-06-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_attackresult_executed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='mac_addr',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
